# Site settings
title: Lime Blast
author: Daniel Hollands
header-img: img/default-bg.jpg
email: your-email@yourdomain.com
description: "The semi-sane ramblings of a developer based in Birmingham"
baseurl: "/"
url: "http://limeblast.co.uk"
twitter_username: LimeBlast
github_username:  LimeBlast
facebook_username:  LimeBlast

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules","package.json","README.md","gulpfile.js"]
